name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - gemfile: Gemfile
        - gemfile: gemfiles/Gemfile
        - gemfile: gemfiles/nested/Gemfile
        - gemfile: test/Gemfile
        - gemfile: test/gemfiles/Gemfile
        - gemfile: test/other/Gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: bundle exec rake test
